import Model from "@/components/Model";
import "./globals.css";

export const metadata = {
  title: "Trello 2.0",
  description: "Generated by Hedi@dev",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6FB]">
        {children}
        <Model />
        </body> 
    </html>
  );
}
